In [4]:
import pygs
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import stats
import statsmodels.formula.api as smf
import os
import json
pd.options.mode.chained_assignment = None #don't show warning flags
%matplotlib inline

from IPython.display import display, HTML
display(HTML(
    '<style>'
        '#notebook { padding-top:0px !important; } ' 
        '.container { width:97% !important; } '
        '.end_space { min-height:0px !important; } '
    '</style>'
))

pd.set_option('display.max_columns', None)
sns.set(rc={'figure.figsize':(16.7,4.27)})

In [59]:
### GET DATA ###
def normalize_decklist(tournament_decklist, record_path):
    cleaned_decklist = pd.json_normalize(tournament_decklist['Decks'], meta=['Date', 'Player', 'Result'], record_path = record_path)
    cleaned_decklist['deck_type'] = record_path
    cleaned_decklist['join_field'] = 1
    return cleaned_decklist

def get_tournament_info(decklist_json):
    tournament_info = pd.json_normalize(decklist_json['Tournament'])
    tournament_info.drop(['Uri'],axis = 1, inplace = True)
    tournament_info['join_field'] = 1 
    return tournament_info

def cleanup_decklist_name(deck_data):
    deck_data.rename({'Count':'card_count', 'CardName':'card_name', 'Date':'tournament_date', 
                        'Player':'player_name', 'Result':'result', 'Name' : 'tournament_name'}, axis = 1, inplace = True)
    
def cleanup_decklist_order(deck_data):
    deck_data = deck_data[['card_name', 'card_count', 'deck_type', 'tournament_name', 'result', 'tournament_date', 'player_name']]
    return deck_data

def cleanup_decklist_data(deck_data):
    cleanup_decklist_name(deck_data)
    deck_data.drop(['join_field'],axis=1, inplace=True)
    deck_data = cleanup_decklist_order(deck_data)
    return deck_data

def get_decklist_data(tournament_decklist):
    main_decklist = normalize_decklist(tournament_decklist, 'Mainboard')
    side_decklist = normalize_decklist(tournament_decklist, 'Sideboard')
    overall_decklist = pd.concat([main_decklist, side_decklist])
    overall_decklist.drop(['Date'],axis=1, inplace=True) #gotten from tournament data
    
    tournament_info = get_tournament_info(tournament_decklist)
    overall_decklist = pd.merge(overall_decklist, tournament_info, on=['join_field'], how='inner')
    overall_decklist = cleanup_decklist_data(overall_decklist)
    return overall_decklist

def create_placement(placement_stop):
    keep_tournament_result = ['7-0', '6-0', '5-0','4-0', '6-1', '5-1', '4-1', '5-2', '1st Place', '2nd Place', '3rd Place'] #can't use fuzzy matching as it'll bring things like 18th place in
    placement = []
    for i in range(4, placement_stop + 1):
        keep_tournament_result.append(str(i) + 'th Place')
    return keep_tournament_result
        
def filter_tournament_result(decklist_data):
    keep_tournament_result = create_placement(8)
    decklist_data = decklist_data[decklist_data['result'].isin(keep_tournament_result)]
    return decklist_data

def get_tournament_decklists(mtg_format, directory):
    overall_decklist_data = pd.DataFrame()

    current_path = os.getcwd()
    current_path = current_path + "\\" + directory
    
    for root, dir_names, file_names in os.walk(current_path):
        print('checking results in: {}'.format(root))
        for f in file_names:
            if mtg_format in f:
                print(" * Adding results from: {}".format(f))
                fname = os.path.join(root, f)
                tournament_decklist = open(fname)
                tournament_decklist = json.load(tournament_decklist)
                tournament_decklist = get_decklist_data(tournament_decklist)
                tournament_decklist = filter_tournament_result(tournament_decklist)
                
                overall_decklist_data = pd.concat([overall_decklist_data, tournament_decklist])
        print("")
    return overall_decklist_data

def create_tournament_date():
    tournament_decklists['tournament_date'] = pd.to_datetime(tournament_decklists['tournament_date']).dt.normalize()
    tournament_decklists['tournament_date'] = tournament_decklists['tournament_date'].dt.tz_localize(None)

### DATA ANALYSIS ###

In [ ]:
generate_data = True
csv_file_name = 'modern_tournament_decklists_17_18.csv'

if generate_data:
    tournament_decklists = get_tournament_decklists('modern', 'deck_data') #only care about modern
    tournament_decklists.to_csv(csv_file_name, encoding='utf-8', index=False)
else:
    print("Data already made, skipping writing process")
    tournament_decklists = pd.read_csv(csv_file_name) 
    tournament_decklists.head(5)

 * Adding results from: modern-challenge-top-8-2017-05-2010640187.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\21

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\22

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\23

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\24

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\25

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\26

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\27
 * Adding results from: modern-challenge-2017-05-2710648056.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\28

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\29

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\30

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\05\31

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\02

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\01

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\03
 * Adding results from: modern-challenge-2017-06-0310664473.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\04

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\05

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\09

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\10
 * Adding results from: modern-challenge-2017-06-1010680754.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\13

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\12

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\16

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\15

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\17
 * Adding results from: modern-challenge-2017-06-1710696535.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\18
 * Adding results from: modern-ptq-finals-2017-06-1810696473.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\19

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\22

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\20

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\23

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\24
 * Adding results from: modern-challenge-2017-06-2410712830.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\21

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\25

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\28

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\27

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\26

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\29

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\06\30

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\01
 * Adding results from: modern-challenge-2017-07-0110728056.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\02

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\03
 * Adding results from: modern-ptq-finals-2017-07-0310728046.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\05

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\04

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\08
 * Adding results from: modern-challenge-2017-07-0810744139.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\09

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\13

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\15
 * Adding results from: modern-challenge-2017-07-1510757685.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\10

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\14

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\16

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\17

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\20

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\18

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\21

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\19

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\22
 * Adding results from: modern-challenge-2017-07-2210770989.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\23

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\27

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\26

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\29
 * Adding results from: modern-challenge-2017-07-2910784864.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\24

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\25

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\30

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\07\31

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\01

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\04

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\03

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\02

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\05
 * Adding results from: modern-challenge-2017-08-0510798963.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\09

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\10

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\13

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\12
 * Adding results from: modern-challenge-2017-08-1210798989.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\16

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\17

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\19
 * Adding results from: modern-challenge-2017-08-1910799015.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\15

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\14

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\20

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\21

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\26
 * Adding results from: modern-challenge-2017-08-2610840501.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\24

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\25

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\27

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\30

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\29

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\23

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\22

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\08\31

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\02
 * Adding results from: modern-challenge-2017-09-0210853759.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\01

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\03
 * Adding results from: modern-ptq-finals-2017-09-0310853755.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\04

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\05

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\09
 * Adding results from: modern-challenge-2017-09-0910866419.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\10
 * Adding results from: modern-ptq-finals-2017-09-1010866415.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\13

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\12

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\15

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\14

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\16
 * Adding results from: modern-challenge-2017-09-1610878902.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\18

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\20

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\17

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\19

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\21

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\22

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\24

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\27

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\25

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\23
 * Adding results from: modern-challenge-2017-09-2310890373.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\28

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\26

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\29

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\09\30
 * Adding results from: modern-challenge-2017-09-3010898107.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\02

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\01

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\03

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\04

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\05

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\07
 * Adding results from: modern-challenge-2017-10-0710913700.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\10

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\09

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\12

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\13

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\14
 * Adding results from: modern-challenge-2017-10-1410927734.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\15

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\18

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\17

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\16

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\19

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\20

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\21
 * Adding results from: modern-challenge-2017-10-2110942631.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\24

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\23

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\22

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\25

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\26

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\27

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\28
 * Adding results from: modern-challenge-2017-10-2810957022.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\30

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\29

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\10\31

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\01

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\03

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\02

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\04
 * Adding results from: modern-challenge-2017-11-0410970617.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\05

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\10

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\09

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\11
 * Adding results from: modern-challenge-2017-11-1110985222.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\12
 * Adding results from: modern-ptq-finals-2017-11-1210985218.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\14

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\16

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\15

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\18
 * Adding results from: modern-challenge-2017-11-1810999457.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\19

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\17

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\21

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\23

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\22

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\24

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\25
 * Adding results from: modern-challenge-2017-11-2511012798.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\20

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\26

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\30

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\27

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\28

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\11\29

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\02
 * Adding results from: modern-challenge-2017-12-0211025687.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\03

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\04

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\09
 * Adding results from: modern-challenge-2017-12-0911039160.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\14

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\12

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\10
 * Adding results from: modern-ptq-finals-2017-12-1011039156.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\15

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\16
 * Adding results from: modern-challenge-2017-12-1611051396.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\17
 * Adding results from: modern-ptq-finals-2017-12-1711051390.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\20

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\18

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\23
 * Adding results from: modern-challenge-2017-12-2311063097.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\22

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\19

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\21

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\24

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\27

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\25

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\28

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\26

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\29

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\31

checking results in: G:\My Drive\CS\modern_cube\deck_data\2017\12\30
 * Adding results from: modern-challenge-2017-12-3011063111.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\04

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\02

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\03

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\01

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\10

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\09

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\13
 * Adding results from: modern-challenge-2018-01-1311104098.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\05

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\12

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\06
 * Adding results from: modern-challenge-2018-01-0611090593.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\14

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\15
 * Adding results from: modern-league-2018-01-152868.json
 * Adding results from: modern-league-2018-01-152844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\16
 * Adding results from: modern-league-2018-01-162868.json
 * Adding results from: modern-league-2018-01-162844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\17
 * Adding results from: modern-league-2018-01-172868.json
 * Adding results from: modern-league-2018-01-172844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\18
 * Adding results from: modern-league-2018-01-182868.json
 * Adding results from: modern-league-2018-01-182844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\19
 * Adding results from: modern-league-2018-01-192844.json
 * Adding results from: modern-league-2018-01-192868.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\20
 * Adding results from: modern-league-2018-01-202868.json
 * Adding results from: modern-league-2018-01-202844.json
 * Adding results from: modern-challenge-2018-01-2011113981.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\21
 * Adding results from: modern-league-2018-01-212868.json
 * Adding results from: modern-league-2018-01-212844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\22
 * Adding results from: modern-league-2018-01-222868.json
 * Adding results from: modern-league-2018-01-222844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\23
 * Adding results from: modern-league-2018-01-232868.json
 * Adding results from: modern-league-2018-01-232844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\24
 * Adding results from: modern-league-2018-01-242868.json
 * Adding results from: modern-league-2018-01-242844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\25
 * Adding results from: modern-league-2018-01-252844.json
 * Adding results from: modern-league-2018-01-252868.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\26
 * Adding results from: modern-league-2018-01-262868.json
 * Adding results from: modern-league-2018-01-262844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\27
 * Adding results from: modern-challenge-2018-01-2711131708.json
 * Adding results from: modern-league-2018-01-272868.json
 * Adding results from: modern-league-2018-01-272844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\28
 * Adding results from: modern-league-2018-01-282868.json
 * Adding results from: modern-league-2018-01-282844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\29
 * Adding results from: modern-league-2018-01-292868.json
 * Adding results from: modern-league-2018-01-292844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\30
 * Adding results from: modern-league-2018-01-302868.json
 * Adding results from: modern-league-2018-01-302844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\01\31
 * Adding results from: modern-league-2018-01-312868.json
 * Adding results from: modern-league-2018-01-312844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\01
 * Adding results from: modern-league-2018-02-012868.json
 * Adding results from: modern-league-2018-02-012844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\02
 * Adding results from: modern-league-2018-02-022868.json
 * Adding results from: modern-league-2018-02-022844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\03
 * Adding results from: modern-league-2018-02-032868.json
 * Adding results from: modern-league-2018-02-032844.json
 * Adding results from: modern-challenge-2018-02-0311145571.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\04
 * Adding results from: modern-league-2018-02-042868.json
 * Adding results from: modern-league-2018-02-042844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\05
 * Adding results from: modern-league-2018-02-052868.json
 * Adding results from: modern-league-2018-02-052844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\06
 * Adding results from: modern-league-2018-02-062868.json
 * Adding results from: modern-league-2018-02-062844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\07
 * Adding results from: modern-league-2018-02-072868.json
 * Adding results from: modern-league-2018-02-072844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\08
 * Adding results from: modern-league-2018-02-082868.json
 * Adding results from: modern-league-2018-02-082844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\09
 * Adding results from: modern-league-2018-02-092868.json
 * Adding results from: modern-league-2018-02-092844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\10
 * Adding results from: modern-league-2018-02-102868.json
 * Adding results from: modern-league-2018-02-102844.json
 * Adding results from: modern-challenge-2018-02-1011160256.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\11
 * Adding results from: modern-league-2018-02-112868.json
 * Adding results from: modern-league-2018-02-112844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\12
 * Adding results from: modern-league-2018-02-122868.json
 * Adding results from: modern-league-2018-02-122844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\13
 * Adding results from: modern-league-2018-02-132868.json
 * Adding results from: modern-league-2018-02-132844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\15
 * Adding results from: modern-league-2018-02-152868.json
 * Adding results from: modern-league-2018-02-152844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\14
 * Adding results from: modern-league-2018-02-142844.json
 * Adding results from: modern-league-2018-02-142868.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\16
 * Adding results from: modern-league-2018-02-162844.json
 * Adding results from: modern-league-2018-02-162868.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\17
 * Adding results from: modern-league-2018-02-172868.json
 * Adding results from: modern-league-2018-02-172844.json
 * Adding results from: modern-challenge-2018-02-1711176218.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\18
 * Adding results from: modern-league-2018-02-182868.json
 * Adding results from: modern-league-2018-02-182844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\19
 * Adding results from: modern-league-2018-02-192868.json
 * Adding results from: modern-league-2018-02-192844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\20
 * Adding results from: modern-league-2018-02-202868.json
 * Adding results from: modern-league-2018-02-202844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\21
 * Adding results from: modern-league-2018-02-212868.json
 * Adding results from: modern-league-2018-02-212844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\22
 * Adding results from: modern-league-2018-02-222868.json
 * Adding results from: modern-league-2018-02-222844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\23
 * Adding results from: modern-league-2018-02-232868.json
 * Adding results from: modern-league-2018-02-232844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\24
 * Adding results from: modern-league-2018-02-242844.json
 * Adding results from: modern-league-2018-02-242868.json
 * Adding results from: modern-challenge-2018-02-2411192645.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\25
 * Adding results from: modern-league-2018-02-252868.json
 * Adding results from: modern-league-2018-02-252844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\26
 * Adding results from: modern-league-2018-02-262844.json
 * Adding results from: modern-league-2018-02-262868.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\27
 * Adding results from: modern-league-2018-02-272868.json
 * Adding results from: modern-league-2018-02-272844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\02\28
 * Adding results from: modern-league-2018-02-282868.json
 * Adding results from: modern-league-2018-02-282844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\01
 * Adding results from: modern-league-2018-03-012868.json
 * Adding results from: modern-league-2018-03-012844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\02
 * Adding results from: modern-league-2018-03-022868.json
 * Adding results from: modern-league-2018-03-022844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\03
 * Adding results from: modern-league-2018-03-032868.json
 * Adding results from: modern-league-2018-03-032844.json
 * Adding results from: modern-challenge-2018-03-0311209914.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\04
 * Adding results from: modern-league-2018-03-042868.json
 * Adding results from: modern-league-2018-03-042844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\05
 * Adding results from: modern-league-2018-03-052844.json
 * Adding results from: modern-league-2018-03-052868.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\06
 * Adding results from: modern-league-2018-03-062868.json
 * Adding results from: modern-league-2018-03-062844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\07
 * Adding results from: modern-league-2018-03-072868.json
 * Adding results from: modern-league-2018-03-072844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\08
 * Adding results from: modern-league-2018-03-082868.json
 * Adding results from: modern-league-2018-03-082844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\09
 * Adding results from: modern-league-2018-03-092868.json
 * Adding results from: modern-league-2018-03-092844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\10
 * Adding results from: modern-league-2018-03-102868.json
 * Adding results from: modern-league-2018-03-102844.json
 * Adding results from: modern-challenge-2018-03-1011227646.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\11
 * Adding results from: modern-league-2018-03-112868.json
 * Adding results from: modern-league-2018-03-112844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\12
 * Adding results from: modern-league-2018-03-122868.json
 * Adding results from: modern-league-2018-03-122844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\13
 * Adding results from: modern-league-2018-03-132868.json
 * Adding results from: modern-league-2018-03-132844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\14
 * Adding results from: modern-league-2018-03-142868.json
 * Adding results from: modern-league-2018-03-142844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\15
 * Adding results from: modern-league-2018-03-152868.json
 * Adding results from: modern-league-2018-03-152844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\16
 * Adding results from: modern-league-2018-03-162868.json
 * Adding results from: modern-league-2018-03-162844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\17
 * Adding results from: modern-league-2018-03-172868.json
 * Adding results from: modern-league-2018-03-172844.json
 * Adding results from: modern-challenge-2018-03-1711244616.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\18
 * Adding results from: modern-league-2018-03-182868.json
 * Adding results from: modern-league-2018-03-182844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\19
 * Adding results from: modern-league-2018-03-192868.json
 * Adding results from: modern-league-2018-03-192844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\20
 * Adding results from: modern-league-2018-03-202868.json
 * Adding results from: modern-league-2018-03-202844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\21
 * Adding results from: modern-league-2018-03-212868.json
 * Adding results from: modern-league-2018-03-212844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\22
 * Adding results from: modern-league-2018-03-222868.json
 * Adding results from: modern-league-2018-03-222844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\23
 * Adding results from: modern-league-2018-03-232868.json
 * Adding results from: modern-league-2018-03-232844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\24
 * Adding results from: modern-league-2018-03-242868.json
 * Adding results from: modern-league-2018-03-242844.json
 * Adding results from: modern-challenge-2018-03-2411260103.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\25
 * Adding results from: modern-league-2018-03-252868.json
 * Adding results from: modern-league-2018-03-252844.json
 * Adding results from: modern-ptq-finals-2018-03-2511260099.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\26
 * Adding results from: modern-league-2018-03-262868.json
 * Adding results from: modern-league-2018-03-262844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\27
 * Adding results from: modern-league-2018-03-272868.json
 * Adding results from: modern-league-2018-03-272844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\28
 * Adding results from: modern-league-2018-03-282868.json
 * Adding results from: modern-league-2018-03-282844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\29
 * Adding results from: modern-league-2018-03-292868.json
 * Adding results from: modern-league-2018-03-292844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\30
 * Adding results from: modern-league-2018-03-302844.json
 * Adding results from: modern-league-2018-03-302868.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\03\31
 * Adding results from: modern-league-2018-03-312868.json
 * Adding results from: modern-league-2018-03-312844.json
 * Adding results from: modern-challenge-2018-03-3111275295.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\01
 * Adding results from: modern-league-2018-04-012868.json
 * Adding results from: modern-league-2018-04-012844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\02
 * Adding results from: modern-league-2018-04-022868.json
 * Adding results from: modern-league-2018-04-022844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\03
 * Adding results from: modern-league-2018-04-032868.json
 * Adding results from: modern-league-2018-04-032844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\04
 * Adding results from: modern-league-2018-04-042868.json
 * Adding results from: modern-league-2018-04-042844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\05
 * Adding results from: modern-league-2018-04-052868.json
 * Adding results from: modern-league-2018-04-052844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\06
 * Adding results from: modern-league-2018-04-062868.json
 * Adding results from: modern-league-2018-04-062844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\07
 * Adding results from: modern-league-2018-04-072868.json
 * Adding results from: modern-league-2018-04-072844.json
 * Adding results from: modern-challenge-2018-04-0711291058.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\08
 * Adding results from: modern-league-2018-04-082868.json
 * Adding results from: modern-league-2018-04-082844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\09
 * Adding results from: modern-league-2018-04-092868.json
 * Adding results from: modern-league-2018-04-092844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\10
 * Adding results from: modern-league-2018-04-102868.json
 * Adding results from: modern-league-2018-04-102844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\11
 * Adding results from: modern-league-2018-04-112868.json
 * Adding results from: modern-league-2018-04-112844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\12
 * Adding results from: modern-league-2018-04-122868.json
 * Adding results from: modern-league-2018-04-122844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\13
 * Adding results from: modern-league-2018-04-132868.json
 * Adding results from: modern-league-2018-04-132844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\14
 * Adding results from: modern-league-2018-04-142868.json
 * Adding results from: modern-league-2018-04-142844.json
 * Adding results from: modern-challenge-2018-04-1411305490.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\15
 * Adding results from: modern-league-2018-04-152868.json
 * Adding results from: modern-league-2018-04-152844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\16
 * Adding results from: modern-league-2018-04-162868.json
 * Adding results from: modern-league-2018-04-162844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\17
 * Adding results from: modern-league-2018-04-172868.json
 * Adding results from: modern-league-2018-04-172844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\18
 * Adding results from: modern-league-2018-04-182868.json
 * Adding results from: modern-league-2018-04-183096.json
 * Adding results from: modern-league-2018-04-183136.json
 * Adding results from: modern-league-2018-04-182844.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\19
 * Adding results from: modern-league-2018-04-193096.json
 * Adding results from: modern-league-2018-04-193136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\20
 * Adding results from: modern-league-2018-04-203136.json
 * Adding results from: modern-league-2018-04-203096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\21
 * Adding results from: modern-league-2018-04-213136.json
 * Adding results from: modern-league-2018-04-213096.json
 * Adding results from: modern-challenge-2018-04-2111322363.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\22
 * Adding results from: modern-league-2018-04-223096.json
 * Adding results from: modern-league-2018-04-223136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\23
 * Adding results from: modern-league-2018-04-233136.json
 * Adding results from: modern-league-2018-04-233096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\24
 * Adding results from: modern-league-2018-04-243096.json
 * Adding results from: modern-league-2018-04-243136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\25
 * Adding results from: modern-league-2018-04-253096.json
 * Adding results from: modern-league-2018-04-253136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\26
 * Adding results from: modern-league-2018-04-263096.json
 * Adding results from: modern-league-2018-04-263136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\27
 * Adding results from: modern-league-2018-04-273096.json
 * Adding results from: modern-league-2018-04-273136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\28
 * Adding results from: modern-league-2018-04-283096.json
 * Adding results from: modern-league-2018-04-283136.json
 * Adding results from: modern-challenge-2018-04-2811333552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\29
 * Adding results from: modern-league-2018-04-293096.json
 * Adding results from: modern-league-2018-04-293136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\04\30
 * Adding results from: modern-league-2018-04-303096.json
 * Adding results from: modern-league-2018-04-303136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\01
 * Adding results from: modern-league-2018-05-013136.json
 * Adding results from: modern-league-2018-05-013096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\02
 * Adding results from: modern-league-2018-05-023096.json
 * Adding results from: modern-league-2018-05-023136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\03
 * Adding results from: modern-league-2018-05-033136.json
 * Adding results from: modern-league-2018-05-033096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\04
 * Adding results from: modern-league-2018-05-043096.json
 * Adding results from: modern-league-2018-05-043136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\05
 * Adding results from: modern-league-2018-05-053136.json
 * Adding results from: modern-challenge-2018-05-0511349017.json
 * Adding results from: modern-league-2018-05-053096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\06
 * Adding results from: modern-league-2018-05-063096.json
 * Adding results from: modern-league-2018-05-063136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\07
 * Adding results from: modern-league-2018-05-073096.json
 * Adding results from: modern-league-2018-05-073136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\08
 * Adding results from: modern-league-2018-05-083096.json
 * Adding results from: modern-league-2018-05-083136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\09
 * Adding results from: modern-league-2018-05-093096.json
 * Adding results from: modern-league-2018-05-093136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\10
 * Adding results from: modern-league-2018-05-103096.json
 * Adding results from: modern-league-2018-05-103136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\11
 * Adding results from: modern-league-2018-05-113096.json
 * Adding results from: modern-league-2018-05-113136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\12
 * Adding results from: modern-league-2018-05-123096.json
 * Adding results from: modern-league-2018-05-123136.json
 * Adding results from: modern-challenge-2018-05-1211364538.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\13
 * Adding results from: modern-league-2018-05-133136.json
 * Adding results from: modern-league-2018-05-133096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\14
 * Adding results from: modern-league-2018-05-143096.json
 * Adding results from: modern-league-2018-05-143136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\15
 * Adding results from: modern-league-2018-05-153136.json
 * Adding results from: modern-league-2018-05-153096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\16
 * Adding results from: modern-league-2018-05-163136.json
 * Adding results from: modern-league-2018-05-163096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\17
 * Adding results from: modern-league-2018-05-173136.json
 * Adding results from: modern-league-2018-05-173096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\18
 * Adding results from: modern-league-2018-05-183136.json
 * Adding results from: modern-league-2018-05-183096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\19
 * Adding results from: modern-league-2018-05-193136.json
 * Adding results from: modern-league-2018-05-193096.json
 * Adding results from: modern-challenge-2018-05-1911379193.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\20
 * Adding results from: modern-league-2018-05-203096.json
 * Adding results from: modern-league-2018-05-203136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\21
 * Adding results from: modern-league-2018-05-213136.json
 * Adding results from: modern-league-2018-05-213096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\22
 * Adding results from: modern-league-2018-05-223136.json
 * Adding results from: modern-league-2018-05-223096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\23
 * Adding results from: modern-league-2018-05-233136.json
 * Adding results from: modern-league-2018-05-233096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\24
 * Adding results from: modern-league-2018-05-243096.json
 * Adding results from: modern-league-2018-05-243136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\25
 * Adding results from: modern-league-2018-05-253136.json
 * Adding results from: modern-league-2018-05-253096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\26
 * Adding results from: modern-league-2018-05-263096.json
 * Adding results from: modern-league-2018-05-263136.json
 * Adding results from: modern-challenge-2018-05-2611393337.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\27
 * Adding results from: modern-league-2018-05-273096.json
 * Adding results from: modern-league-2018-05-273136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\28
 * Adding results from: modern-league-2018-05-283096.json
 * Adding results from: modern-league-2018-05-283136.json
 * Adding results from: modern-ptq-finals-2018-05-2811393333.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\29
 * Adding results from: modern-league-2018-05-293096.json
 * Adding results from: modern-league-2018-05-293136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\30
 * Adding results from: modern-league-2018-05-303136.json
 * Adding results from: modern-league-2018-05-303096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\05\31
 * Adding results from: modern-league-2018-05-313136.json
 * Adding results from: modern-league-2018-05-313096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\01
 * Adding results from: modern-league-2018-06-013136.json
 * Adding results from: modern-league-2018-06-013096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\02
 * Adding results from: modern-league-2018-06-023096.json
 * Adding results from: modern-league-2018-06-023136.json
 * Adding results from: modern-challenge-2018-06-0211407038.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\03
 * Adding results from: modern-league-2018-06-033096.json
 * Adding results from: modern-league-2018-06-033136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\04
 * Adding results from: modern-league-2018-06-043096.json
 * Adding results from: modern-league-2018-06-043136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\05
 * Adding results from: modern-league-2018-06-053096.json
 * Adding results from: modern-league-2018-06-053136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\06
 * Adding results from: modern-league-2018-06-063136.json
 * Adding results from: modern-league-2018-06-063096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\07
 * Adding results from: modern-league-2018-06-073096.json
 * Adding results from: modern-league-2018-06-073136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\08
 * Adding results from: modern-league-2018-06-083136.json
 * Adding results from: modern-league-2018-06-083096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\09
 * Adding results from: modern-league-2018-06-093136.json
 * Adding results from: modern-league-2018-06-093096.json
 * Adding results from: modern-challenge-2018-06-0911421572.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\10
 * Adding results from: modern-league-2018-06-103136.json
 * Adding results from: modern-league-2018-06-103096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\11
 * Adding results from: modern-league-2018-06-113096.json
 * Adding results from: modern-league-2018-06-113136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\12
 * Adding results from: modern-league-2018-06-123096.json
 * Adding results from: modern-league-2018-06-123136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\14
 * Adding results from: modern-league-2018-06-143096.json
 * Adding results from: modern-league-2018-06-143136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\13
 * Adding results from: modern-league-2018-06-133136.json
 * Adding results from: modern-league-2018-06-133096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\15
 * Adding results from: modern-league-2018-06-153096.json
 * Adding results from: modern-league-2018-06-153136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\16
 * Adding results from: modern-league-2018-06-163096.json
 * Adding results from: modern-league-2018-06-163136.json
 * Adding results from: modern-challenge-2018-06-1611434971.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\17
 * Adding results from: modern-league-2018-06-173136.json
 * Adding results from: modern-league-2018-06-173096.json
 * Adding results from: modern-ptq-finals-2018-06-1711434967.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\18
 * Adding results from: modern-league-2018-06-183136.json
 * Adding results from: modern-league-2018-06-183096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\19
 * Adding results from: modern-league-2018-06-193096.json
 * Adding results from: modern-league-2018-06-193136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\20
 * Adding results from: modern-league-2018-06-203136.json
 * Adding results from: modern-league-2018-06-203096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\21
 * Adding results from: modern-league-2018-06-213096.json
 * Adding results from: modern-league-2018-06-213136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\22
 * Adding results from: modern-league-2018-06-223136.json
 * Adding results from: modern-league-2018-06-223096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\23
 * Adding results from: modern-league-2018-06-233136.json
 * Adding results from: modern-league-2018-06-233096.json
 * Adding results from: modern-challenge-2018-06-2311448057.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\24
 * Adding results from: modern-league-2018-06-243096.json
 * Adding results from: modern-league-2018-06-243136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\25
 * Adding results from: modern-league-2018-06-253096.json
 * Adding results from: modern-league-2018-06-253136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\26
 * Adding results from: modern-league-2018-06-263096.json
 * Adding results from: modern-league-2018-06-263136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\27
 * Adding results from: modern-league-2018-06-273096.json
 * Adding results from: modern-league-2018-06-273136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\28
 * Adding results from: modern-league-2018-06-283136.json
 * Adding results from: modern-league-2018-06-283096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\29
 * Adding results from: modern-league-2018-06-293096.json
 * Adding results from: modern-league-2018-06-293136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\06\30
 * Adding results from: modern-league-2018-06-303096.json
 * Adding results from: modern-league-2018-06-303136.json
 * Adding results from: modern-challenge-2018-06-3011460907.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\01
 * Adding results from: modern-league-2018-07-013096.json
 * Adding results from: modern-league-2018-07-013136.json
 * Adding results from: modern-ptq-finals-2018-07-0111460903.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\02
 * Adding results from: modern-league-2018-07-023096.json
 * Adding results from: modern-league-2018-07-023136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\03
 * Adding results from: modern-league-2018-07-033096.json
 * Adding results from: modern-league-2018-07-033136.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\04
 * Adding results from: modern-league-2018-07-043136.json
 * Adding results from: modern-league-2018-07-043096.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\05
 * Adding results from: modern-league-2018-07-053136.json
 * Adding results from: modern-league-2018-07-053096.json
 * Adding results from: modern-league-2018-07-053306.json
 * Adding results from: modern-league-2018-07-053346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\06
 * Adding results from: modern-league-2018-07-063346.json
 * Adding results from: modern-league-2018-07-063306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\07
 * Adding results from: modern-league-2018-07-073346.json
 * Adding results from: modern-league-2018-07-073306.json
 * Adding results from: modern-challenge-2018-07-0711476179.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\08
 * Adding results from: modern-league-2018-07-083346.json
 * Adding results from: modern-league-2018-07-083306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\09
 * Adding results from: modern-league-2018-07-093306.json
 * Adding results from: modern-league-2018-07-093346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\10
 * Adding results from: modern-league-2018-07-103346.json
 * Adding results from: modern-league-2018-07-103306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\11
 * Adding results from: modern-league-2018-07-113346.json
 * Adding results from: modern-league-2018-07-113306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\12
 * Adding results from: modern-league-2018-07-123346.json
 * Adding results from: modern-league-2018-07-123306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\13
 * Adding results from: modern-league-2018-07-133306.json
 * Adding results from: modern-league-2018-07-133346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\14
 * Adding results from: modern-league-2018-07-143306.json
 * Adding results from: modern-league-2018-07-143346.json
 * Adding results from: modern-challenge-2018-07-1411482823.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\15
 * Adding results from: modern-league-2018-07-153346.json
 * Adding results from: modern-league-2018-07-153306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\16
 * Adding results from: modern-league-2018-07-163306.json
 * Adding results from: modern-league-2018-07-163346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\17
 * Adding results from: modern-league-2018-07-173346.json
 * Adding results from: modern-league-2018-07-173306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\18
 * Adding results from: modern-league-2018-07-183346.json
 * Adding results from: modern-league-2018-07-183306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\19
 * Adding results from: modern-league-2018-07-193346.json
 * Adding results from: modern-league-2018-07-193306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\20
 * Adding results from: modern-league-2018-07-203346.json
 * Adding results from: modern-league-2018-07-203306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\21
 * Adding results from: modern-league-2018-07-213306.json
 * Adding results from: modern-challenge-2018-07-2111501767.json
 * Adding results from: modern-league-2018-07-213346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\22
 * Adding results from: modern-league-2018-07-223346.json
 * Adding results from: modern-league-2018-07-223306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\23
 * Adding results from: modern-league-2018-07-233346.json
 * Adding results from: modern-league-2018-07-233306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\24
 * Adding results from: modern-league-2018-07-243346.json
 * Adding results from: modern-league-2018-07-243306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\25
 * Adding results from: modern-league-2018-07-253306.json
 * Adding results from: modern-league-2018-07-253346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\26
 * Adding results from: modern-league-2018-07-263306.json
 * Adding results from: modern-league-2018-07-263346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\27
 * Adding results from: modern-league-2018-07-273306.json
 * Adding results from: modern-league-2018-07-273346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\28
 * Adding results from: modern-league-2018-07-283306.json
 * Adding results from: modern-league-2018-07-283346.json
 * Adding results from: modern-challenge-2018-07-2811515717.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\29
 * Adding results from: modern-league-2018-07-293306.json
 * Adding results from: modern-league-2018-07-293346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\30
 * Adding results from: modern-league-2018-07-303346.json
 * Adding results from: modern-league-2018-07-303306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\07\31
 * Adding results from: modern-league-2018-07-313346.json
 * Adding results from: modern-league-2018-07-313306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\01
 * Adding results from: modern-league-2018-08-013306.json
 * Adding results from: modern-league-2018-08-013346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\02
 * Adding results from: modern-league-2018-08-023346.json
 * Adding results from: modern-league-2018-08-023306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\03
 * Adding results from: modern-league-2018-08-033346.json
 * Adding results from: modern-league-2018-08-033306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\04
 * Adding results from: modern-league-2018-08-043346.json
 * Adding results from: modern-league-2018-08-043306.json
 * Adding results from: modern-challenge-2018-08-0411529383.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\05
 * Adding results from: modern-league-2018-08-053346.json
 * Adding results from: modern-league-2018-08-053306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\06
 * Adding results from: modern-league-2018-08-063306.json
 * Adding results from: modern-league-2018-08-063346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\07
 * Adding results from: modern-league-2018-08-073306.json
 * Adding results from: modern-league-2018-08-073346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\08
 * Adding results from: modern-league-2018-08-083306.json
 * Adding results from: modern-league-2018-08-083346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\09
 * Adding results from: modern-league-2018-08-093346.json
 * Adding results from: modern-league-2018-08-093306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\10
 * Adding results from: modern-league-2018-08-103346.json
 * Adding results from: modern-league-2018-08-103306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\11
 * Adding results from: modern-league-2018-08-113346.json
 * Adding results from: modern-league-2018-08-113306.json
 * Adding results from: modern-challenge-2018-08-1111542642.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\12
 * Adding results from: modern-league-2018-08-123346.json
 * Adding results from: modern-league-2018-08-123306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\13
 * Adding results from: modern-league-2018-08-133346.json
 * Adding results from: modern-league-2018-08-133306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\14
 * Adding results from: modern-league-2018-08-143346.json
 * Adding results from: modern-league-2018-08-143306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\15
 * Adding results from: modern-league-2018-08-153306.json
 * Adding results from: modern-league-2018-08-153346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\16
 * Adding results from: modern-league-2018-08-163306.json
 * Adding results from: modern-league-2018-08-163346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\17
 * Adding results from: modern-league-2018-08-173306.json
 * Adding results from: modern-league-2018-08-173346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\18
 * Adding results from: modern-league-2018-08-183306.json
 * Adding results from: modern-league-2018-08-183346.json
 * Adding results from: modern-challenge-2018-08-1811555876.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\19
 * Adding results from: modern-league-2018-08-193306.json
 * Adding results from: modern-league-2018-08-193346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\20
 * Adding results from: modern-league-2018-08-203346.json
 * Adding results from: modern-league-2018-08-203306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\21
 * Adding results from: modern-league-2018-08-213306.json
 * Adding results from: modern-league-2018-08-213346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\22
 * Adding results from: modern-league-2018-08-223306.json
 * Adding results from: modern-league-2018-08-223346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\23
 * Adding results from: modern-league-2018-08-233346.json
 * Adding results from: modern-league-2018-08-233306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\24
 * Adding results from: modern-league-2018-08-243306.json
 * Adding results from: modern-league-2018-08-243346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\25
 * Adding results from: modern-league-2018-08-253306.json
 * Adding results from: modern-league-2018-08-253346.json
 * Adding results from: modern-challenge-2018-08-2511568480.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\26
 * Adding results from: modern-league-2018-08-263306.json
 * Adding results from: modern-league-2018-08-263346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\27
 * Adding results from: modern-league-2018-08-273306.json
 * Adding results from: modern-league-2018-08-273346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\28
 * Adding results from: modern-league-2018-08-283306.json
 * Adding results from: modern-league-2018-08-283346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\29
 * Adding results from: modern-league-2018-08-293346.json
 * Adding results from: modern-league-2018-08-293306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\30
 * Adding results from: modern-league-2018-08-303306.json
 * Adding results from: modern-league-2018-08-303346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\08\31
 * Adding results from: modern-league-2018-08-313306.json
 * Adding results from: modern-league-2018-08-313346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\01
 * Adding results from: modern-league-2018-09-013306.json
 * Adding results from: modern-league-2018-09-013346.json
 * Adding results from: modern-challenge-2018-09-0111580423.json
 * Adding results from: modern-ptq-finals-2018-09-0111580416.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\02
 * Adding results from: modern-league-2018-09-023306.json
 * Adding results from: modern-league-2018-09-023346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\03
 * Adding results from: modern-league-2018-09-033346.json
 * Adding results from: modern-league-2018-09-033306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\04
 * Adding results from: modern-league-2018-09-043306.json
 * Adding results from: modern-league-2018-09-043346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\05
 * Adding results from: modern-league-2018-09-053306.json
 * Adding results from: modern-league-2018-09-053346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\06
 * Adding results from: modern-league-2018-09-063346.json
 * Adding results from: modern-league-2018-09-063306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\07
 * Adding results from: modern-league-2018-09-073306.json
 * Adding results from: modern-league-2018-09-073346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\08
 * Adding results from: modern-league-2018-09-083306.json
 * Adding results from: modern-league-2018-09-083346.json
 * Adding results from: modern-challenge-2018-09-0811592809.json
 * Adding results from: modern-ptq-finals-2018-09-0811592802.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\09
 * Adding results from: modern-league-2018-09-093306.json
 * Adding results from: modern-league-2018-09-093346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\10
 * Adding results from: modern-league-2018-09-103346.json
 * Adding results from: modern-league-2018-09-103306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\11
 * Adding results from: modern-league-2018-09-113346.json
 * Adding results from: modern-league-2018-09-113306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\12
 * Adding results from: modern-league-2018-09-123346.json
 * Adding results from: modern-league-2018-09-123306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\13
 * Adding results from: modern-league-2018-09-133306.json
 * Adding results from: modern-league-2018-09-133346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\14
 * Adding results from: modern-league-2018-09-143346.json
 * Adding results from: modern-league-2018-09-143306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\15
 * Adding results from: modern-league-2018-09-153306.json
 * Adding results from: modern-challenge-2018-09-1511604271.json
 * Adding results from: modern-league-2018-09-153346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\16
 * Adding results from: modern-league-2018-09-163346.json
 * Adding results from: modern-league-2018-09-163306.json
 * Adding results from: modern-ptq-finals-2018-09-1611604267.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\17
 * Adding results from: modern-league-2018-09-173306.json
 * Adding results from: modern-league-2018-09-173346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\18
 * Adding results from: modern-league-2018-09-183346.json
 * Adding results from: modern-league-2018-09-183306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\19
 * Adding results from: modern-league-2018-09-193306.json
 * Adding results from: modern-league-2018-09-193346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\20
 * Adding results from: modern-league-2018-09-203346.json
 * Adding results from: modern-league-2018-09-203306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\21
 * Adding results from: modern-league-2018-09-213306.json
 * Adding results from: modern-league-2018-09-213346.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\22
 * Adding results from: modern-league-2018-09-223346.json
 * Adding results from: modern-challenge-2018-09-2211615687.json
 * Adding results from: modern-league-2018-09-223306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\23
 * Adding results from: modern-league-2018-09-233346.json
 * Adding results from: modern-league-2018-09-233306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\24
 * Adding results from: modern-league-2018-09-243346.json
 * Adding results from: modern-league-2018-09-243306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\25
 * Adding results from: modern-league-2018-09-253346.json
 * Adding results from: modern-league-2018-09-253306.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\26
 * Adding results from: modern-league-2018-09-263346.json
 * Adding results from: modern-league-2018-09-263306.json
 * Adding results from: modern-league-2018-09-263520.json
 * Adding results from: modern-league-2018-09-263552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\27
 * Adding results from: modern-league-2018-09-273520.json
 * Adding results from: modern-league-2018-09-273552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\28
 * Adding results from: modern-league-2018-09-283520.json
 * Adding results from: modern-league-2018-09-283552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\29
 * Adding results from: modern-challenge-2018-09-2911627368.json
 * Adding results from: modern-league-2018-09-293552.json
 * Adding results from: modern-league-2018-09-293520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\09\30
 * Adding results from: modern-league-2018-09-303520.json
 * Adding results from: modern-league-2018-09-303552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\01
 * Adding results from: modern-league-2018-10-013520.json
 * Adding results from: modern-league-2018-10-013552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\02
 * Adding results from: modern-league-2018-10-023552.json
 * Adding results from: modern-league-2018-10-023520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\03
 * Adding results from: modern-league-2018-10-033552.json
 * Adding results from: modern-league-2018-10-033520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\04
 * Adding results from: modern-league-2018-10-043520.json
 * Adding results from: modern-league-2018-10-043552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\05
 * Adding results from: modern-league-2018-10-053520.json
 * Adding results from: modern-league-2018-10-053552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\06
 * Adding results from: modern-league-2018-10-063520.json
 * Adding results from: modern-league-2018-10-063552.json
 * Adding results from: modern-challenge-2018-10-0611633791.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\07
 * Adding results from: modern-league-2018-10-073520.json
 * Adding results from: modern-league-2018-10-073552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\08
 * Adding results from: modern-league-2018-10-083520.json
 * Adding results from: modern-league-2018-10-083552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\09
 * Adding results from: modern-league-2018-10-093520.json
 * Adding results from: modern-league-2018-10-093552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\10
 * Adding results from: modern-league-2018-10-103520.json
 * Adding results from: modern-league-2018-10-103552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\11
 * Adding results from: modern-league-2018-10-113520.json
 * Adding results from: modern-league-2018-10-113552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\12
 * Adding results from: modern-league-2018-10-123552.json
 * Adding results from: modern-league-2018-10-123520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\13
 * Adding results from: modern-league-2018-10-133552.json
 * Adding results from: modern-league-2018-10-133520.json
 * Adding results from: modern-challenge-2018-10-1311648227.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\14
 * Adding results from: modern-league-2018-10-143520.json
 * Adding results from: modern-league-2018-10-143552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\15
 * Adding results from: modern-league-2018-10-153520.json
 * Adding results from: modern-league-2018-10-153552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\16
 * Adding results from: modern-league-2018-10-163520.json
 * Adding results from: modern-league-2018-10-163552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\17
 * Adding results from: modern-league-2018-10-173552.json
 * Adding results from: modern-league-2018-10-173520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\18
 * Adding results from: modern-league-2018-10-183520.json
 * Adding results from: modern-league-2018-10-183552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\19
 * Adding results from: modern-league-2018-10-193520.json
 * Adding results from: modern-league-2018-10-193552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\20
 * Adding results from: modern-league-2018-10-203552.json
 * Adding results from: modern-challenge-2018-10-2011659813.json
 * Adding results from: modern-league-2018-10-203520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\21
 * Adding results from: modern-league-2018-10-213552.json
 * Adding results from: modern-league-2018-10-213520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\22
 * Adding results from: modern-league-2018-10-223552.json
 * Adding results from: modern-league-2018-10-223520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\23
 * Adding results from: modern-league-2018-10-233520.json
 * Adding results from: modern-league-2018-10-233552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\24
 * Adding results from: modern-league-2018-10-243520.json
 * Adding results from: modern-league-2018-10-243552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\25
 * Adding results from: modern-league-2018-10-253520.json
 * Adding results from: modern-league-2018-10-253552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\26
 * Adding results from: modern-league-2018-10-263520.json
 * Adding results from: modern-league-2018-10-263552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\27
 * Adding results from: modern-league-2018-10-273520.json
 * Adding results from: modern-league-2018-10-273552.json
 * Adding results from: modern-challenge-2018-10-2711670671.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\28
 * Adding results from: modern-league-2018-10-283520.json
 * Adding results from: modern-league-2018-10-283552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\29
 * Adding results from: modern-league-2018-10-293520.json
 * Adding results from: modern-league-2018-10-293552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\30
 * Adding results from: modern-league-2018-10-303520.json
 * Adding results from: modern-league-2018-10-303552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\10\31
 * Adding results from: modern-league-2018-10-313552.json
 * Adding results from: modern-league-2018-10-313520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\01
 * Adding results from: modern-league-2018-11-013520.json
 * Adding results from: modern-league-2018-11-013552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\02
 * Adding results from: modern-league-2018-11-023552.json
 * Adding results from: modern-league-2018-11-023520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\03
 * Adding results from: modern-league-2018-11-033552.json
 * Adding results from: modern-challenge-2018-11-0311681656.json
 * Adding results from: modern-league-2018-11-033520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\04
 * Adding results from: modern-league-2018-11-043552.json
 * Adding results from: modern-league-2018-11-043520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\05
 * Adding results from: modern-league-2018-11-053520.json
 * Adding results from: modern-league-2018-11-053552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\06
 * Adding results from: modern-league-2018-11-063520.json
 * Adding results from: modern-league-2018-11-063552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\07
 * Adding results from: modern-league-2018-11-073520.json
 * Adding results from: modern-league-2018-11-073552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\08
 * Adding results from: modern-league-2018-11-083520.json
 * Adding results from: modern-league-2018-11-083552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\09
 * Adding results from: modern-league-2018-11-093520.json
 * Adding results from: modern-league-2018-11-093552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\10
 * Adding results from: modern-league-2018-11-103520.json
 * Adding results from: modern-challenge-2018-11-1011692425.json
 * Adding results from: modern-league-2018-11-103552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\11
 * Adding results from: modern-league-2018-11-113552.json
 * Adding results from: modern-league-2018-11-113520.json
 * Adding results from: modern-ptq-finals-2018-11-1111692421.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\12
 * Adding results from: modern-league-2018-11-123552.json
 * Adding results from: modern-league-2018-11-123520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\13
 * Adding results from: modern-league-2018-11-133552.json
 * Adding results from: modern-league-2018-11-133520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\14
 * Adding results from: modern-league-2018-11-143552.json
 * Adding results from: modern-league-2018-11-143520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\15
 * Adding results from: modern-league-2018-11-153552.json
 * Adding results from: modern-league-2018-11-153520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\16
 * Adding results from: modern-league-2018-11-163520.json
 * Adding results from: modern-league-2018-11-163552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\17
 * Adding results from: modern-league-2018-11-173520.json
 * Adding results from: modern-challenge-2018-11-1711703455.json
 * Adding results from: modern-league-2018-11-173552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\18
 * Adding results from: modern-league-2018-11-183520.json
 * Adding results from: modern-league-2018-11-183552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\19
 * Adding results from: modern-league-2018-11-193552.json
 * Adding results from: modern-league-2018-11-193520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\20
 * Adding results from: modern-league-2018-11-203552.json
 * Adding results from: modern-league-2018-11-203520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\21
 * Adding results from: modern-league-2018-11-213520.json
 * Adding results from: modern-league-2018-11-213552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\22
 * Adding results from: modern-league-2018-11-223552.json
 * Adding results from: modern-league-2018-11-223520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\23
 * Adding results from: modern-league-2018-11-233552.json
 * Adding results from: modern-league-2018-11-233520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\24
 * Adding results from: modern-league-2018-11-243520.json
 * Adding results from: modern-league-2018-11-243552.json
 * Adding results from: modern-challenge-2018-11-2411712646.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\25
 * Adding results from: modern-league-2018-11-253520.json
 * Adding results from: modern-league-2018-11-253552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\26
 * Adding results from: modern-league-2018-11-263520.json
 * Adding results from: modern-league-2018-11-263552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\27
 * Adding results from: modern-league-2018-11-273520.json
 * Adding results from: modern-league-2018-11-273552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\28
 * Adding results from: modern-league-2018-11-283520.json
 * Adding results from: modern-league-2018-11-283552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\29
 * Adding results from: modern-league-2018-11-293520.json
 * Adding results from: modern-league-2018-11-293552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\11\30
 * Adding results from: modern-league-2018-11-303520.json
 * Adding results from: modern-league-2018-11-303552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\01
 * Adding results from: modern-league-2018-12-013552.json
 * Adding results from: modern-challenge-2018-12-0111724054.json
 * Adding results from: modern-league-2018-12-013520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\02
 * Adding results from: modern-league-2018-12-023520.json
 * Adding results from: modern-league-2018-12-023552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\03
 * Adding results from: modern-league-2018-12-033520.json
 * Adding results from: modern-league-2018-12-033552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\04
 * Adding results from: modern-league-2018-12-043520.json
 * Adding results from: modern-league-2018-12-043552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\05
 * Adding results from: modern-league-2018-12-053520.json
 * Adding results from: modern-league-2018-12-053552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\06
 * Adding results from: modern-league-2018-12-063520.json
 * Adding results from: modern-league-2018-12-063552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\07
 * Adding results from: modern-league-2018-12-073520.json
 * Adding results from: modern-league-2018-12-073552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\08
 * Adding results from: modern-league-2018-12-083520.json
 * Adding results from: modern-challenge-2018-12-0811733241.json
 * Adding results from: modern-league-2018-12-083552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\09
 * Adding results from: modern-league-2018-12-093520.json
 * Adding results from: modern-league-2018-12-093552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\10
 * Adding results from: modern-league-2018-12-103520.json
 * Adding results from: modern-league-2018-12-103552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\11
 * Adding results from: modern-league-2018-12-113552.json
 * Adding results from: modern-league-2018-12-113520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\12
 * Adding results from: modern-league-2018-12-123552.json
 * Adding results from: modern-league-2018-12-123520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\13
 * Adding results from: modern-league-2018-12-133520.json
 * Adding results from: modern-league-2018-12-133552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\14
 * Adding results from: modern-league-2018-12-143520.json
 * Adding results from: modern-league-2018-12-143552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\15
 * Adding results from: modern-league-2018-12-153520.json
 * Adding results from: modern-challenge-2018-12-1511740707.json
 * Adding results from: modern-league-2018-12-153552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\16
 * Adding results from: modern-league-2018-12-163520.json
 * Adding results from: modern-league-2018-12-163552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\17
 * Adding results from: modern-league-2018-12-173552.json
 * Adding results from: modern-league-2018-12-173520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\18
 * Adding results from: modern-league-2018-12-183520.json
 * Adding results from: modern-league-2018-12-183552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\19
 * Adding results from: modern-league-2018-12-193520.json
 * Adding results from: modern-league-2018-12-193552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\20
 * Adding results from: modern-league-2018-12-203520.json
 * Adding results from: modern-league-2018-12-203552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\21
 * Adding results from: modern-league-2018-12-213552.json
 * Adding results from: modern-league-2018-12-213520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\22
 * Adding results from: modern-challenge-2018-12-2211747389.json
 * Adding results from: modern-league-2018-12-223520.json
 * Adding results from: modern-league-2018-12-223552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\23
 * Adding results from: modern-league-2018-12-233552.json
 * Adding results from: modern-league-2018-12-233520.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\24
 * Adding results from: modern-league-2018-12-243520.json
 * Adding results from: modern-league-2018-12-243552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\25
 * Adding results from: modern-league-2018-12-253520.json
 * Adding results from: modern-league-2018-12-253552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\26
 * Adding results from: modern-league-2018-12-263520.json
 * Adding results from: modern-league-2018-12-263552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\27
 * Adding results from: modern-league-2018-12-273520.json
 * Adding results from: modern-league-2018-12-273552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\28
 * Adding results from: modern-league-2018-12-283520.json
 * Adding results from: modern-league-2018-12-283552.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\29
 * Adding results from: modern-league-2018-12-293520.json
 * Adding results from: modern-league-2018-12-293552.json
 * Adding results from: modern-challenge-2018-12-2911747402.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\30
 * Adding results from: modern-league-2018-12-303552.json
 * Adding results from: modern-league-2018-12-303520.json
 * Adding results from: modern-mcq-finals-2018-12-3011747383.json

checking results in: G:\My Drive\CS\modern_cube\deck_data\2018\12\31
 * Adding results from: modern-league-2018-12-313552.json
 * Adding results from: modern-league-2018-12-313520.json

In [61]:
tournament_decklists = pd.read_csv(csv_file_name)


create_tournament_date()
tournament_decklists.head(5)

,card_name,card_count,deck_type,tournament_name,result,tournament_date,player_name
0,Blood Crypt,1,Mainboard,Modern PTQ Preliminary,5-0,2017-01-01,__Ghost__
1,Bloodstained Mire,1,Mainboard,Modern PTQ Preliminary,5-0,2017-01-01,__Ghost__
2,Delver of Secrets,4,Mainboard,Modern PTQ Preliminary,5-0,2017-01-01,__Ghost__
3,Gitaxian Probe,3,Mainboard,Modern PTQ Preliminary,5-0,2017-01-01,__Ghost__
4,Island,2,Mainboard,Modern PTQ Preliminary,5-0,2017-01-01,__Ghost__

In [57]:
tournament_decklists.dtypes

card_name                  object
card_count                  int64
deck_type                  object
tournament_name            object
result                     object
tournament_date    datetime64[ns]
player_name                object
dtype: object

In [62]:
### SCRYFALL DATA ###

,object,id,oracle_id,multiverse_ids,mtgo_id,mtgo_foil_id,tcgplayer_id,cardmarket_id,name,lang,released_at,uri,scryfall_uri,layout,highres_image,image_status,mana_cost,cmc,type_line,oracle_text,colors,color_identity,keywords,games,reserved,foil,nonfoil,finishes,oversized,promo,reprint,variation,set_id,set,set_name,set_type,set_uri,set_search_uri,scryfall_set_uri,rulings_uri,prints_search_uri,collector_number,digital,rarity,flavor_text,card_back_id,artist,artist_ids,illustration_id,border_color,frame,full_art,textless,booster,story_spotlight,edhrec_rank,image_uris.small,image_uris.normal,image_uris.large,image_uris.png,image_uris.art_crop,image_uris.border_crop,legalities.standard,legalities.future,legalities.historic,legalities.timeless,legalities.gladiator,legalities.pioneer,legalities.explorer,legalities.modern,legalities.legacy,legalities.pauper,legalities.vintage,legalities.penny,legalities.commander,legalities.oathbreaker,legalities.standardbrawl,legalities.brawl,legalities.alchemy,legalities.paupercommander,legalities.duel,legalities.oldschool,legalities.premodern,legalities.predh,prices.usd,prices.usd_foil,prices.usd_etched,prices.eur,prices.eur_foil,prices.tix,related_uris.gatherer,related_uris.tcgplayer_infinite_articles,related_uris.tcgplayer_infinite_decks,related_uris.edhrec,purchase_uris.tcgplayer,purchase_uris.cardmarket,purchase_uris.cardhoarder,security_stamp,preview.source,preview.source_uri,preview.previewed_at,power,toughness,penny_rank,arena_id,promo_types,all_parts,frame_effects,produced_mana,watermark,card_faces,tcgplayer_etched_id,loyalty,life_modifier,hand_modifier,attraction_lights,color_indicator,content_warning
0,card,86bf43b1-8d4e-4759-bb2d-0b2e03ba7012,0004ebd0-dfd6-4276-b4a6-de0003e94237,[15862],15870.0,15871.0,3094.0,3081.0,Static Orb,en,2001-04-11,https://api.scryfall.com/cards/86bf43b1-8d4e-4...,https://scryfall.com/card/7ed/319/static-orb?u...,normal,True,highres_scan,{3},3.0,Artifact,"As long as Static Orb is untapped, players can...",[],[],[],"[paper, mtgo]",False,False,True,[nonfoil],False,False,True,False,230f38aa-9511-4db8-a3aa-aeddbc3f7bb9,7ed,Seventh Edition,core,https://api.scryfall.com/sets/230f38aa-9511-4d...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/7ed?utm_source=api,https://api.scryfall.com/cards/86bf43b1-8d4e-4...,https://api.scryfall.com/cards/search?order=re...,319,False,rare,The warriors fought against the paralyzing wav...,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Terese Nielsen,[eb55171c-2342-45f4-a503-2d5a75baf752],6f8b3b2c-252f-4f95-b621-712c82be38b5,white,1997,False,False,True,False,3863.0,https://cards.scryfall.io/small/front/8/6/86bf...,https://cards.scryfall.io/normal/front/8/6/86b...,https://cards.scryfall.io/large/front/8/6/86bf...,https://cards.scryfall.io/png/front/8/6/86bf43...,https://cards.scryfall.io/art_crop/front/8/6/8...,https://cards.scryfall.io/border_crop/front/8/...,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,not_legal,legal,legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,legal,19.41,None,None,9.42,None,0.24,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Static+Orb,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/15870?affili...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,card,7050735c-b232-47a6-a342-01795bfd0d46,0006faf6-7a61-426c-9034-579f2cfcfa83,[370780],49283.0,49284.0,69965.0,262945.0,Sensory Deprivation,en,2013-07-19,https://api.scryfall.com/cards/7050735c-b232-4...,https://scryfall.com/card/m14/71/sensory-depri...,normal,True,highres_scan,{U},1.0,Enchantment — Aura,Enchant creature\nEnchanted creature gets -3/-0.,[U],[U],[Enchant],"[paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,True,False,e03ee1c0-ecd2-4fcc-ac3c-e8fdb103a847,m14,Magic 2014,core,https://api.scryfall.com/sets/e03ee1c0-ecd2-4f...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/m14?utm_source=api,https://api.scryfall.com/cards/7050735c-b232-4...,https://api.scryfall.com/cards/search?order=re...,71,False,common,"They call it ""stitcher's anesthesia,"" a spell ...",0aeebaf5-8c7d-4636-9e82-8c27447861f7,Steven Belledin,[f07d73b9-52a0-4fe5-858b-61f7b42174a5],3c9e9355-4dcd-411c-b85f-47386e94854b,black,2003,False,False,True,False,25688.0,https://cards.scryfall.io/small/front/7/0/7050...,https://cards.scryfall.io/normal/front/7/0/705...,https://cards.scryfall.io/large/front/7/0/7050...,https://cards.scryfall.io/png/front/7/0/705073...,https://cards.scryfall.io/art_crop/front/7/0/7...,https://cards.scryfall.io/border_crop/front/7/...,not_legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,not_legal,not_legal,legal,legal,not_legal,not_legal,not_legal,0.04,0.21,None,0.07,0.17,0.04,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Sensory+Deprivation,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/49283?affili...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,card,e718b21b-46d1-4844-985c-52745657b1ac,0007c283-5b7a-4c00-9ca1-b455c8dff8c3,[470580],77122.0,NaN,196536.0,391692.0,Road of Return,en,2019-08-23,https://api.scryfall.com/cards/e718b21b-46d1-4...,https://scryfall.com/card/c19/34/road-of-retur...,normal,True,highres_scan,{G}{G},2.0,Sorcery,Choose one —\n• Return target permanent card f...,[G],[G],[Entwine],"[paper, mtgo]",False,False,True,[nonfoil],False,False,False,False,0fa3ccbb-d86d-4a2e-a55e-c4979c4feeb2,c19,Commander 2019,commander,https://api.scryfall.com/sets/0fa3ccbb-d86d-4a...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/c19?utm_source=api,https://api.scryfall.com/cards/e718b21b-46d1-4...,https://api.scryfall.com/cards/search?order=re...,34,False,rare,NaN,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Jonas De Ro,[561ebf9e-8d93-4b57-8156-8826d0c19601],279f7cef-a81c-4b43-98a0-937f3c355b5e,black,2015,False,False,False,False,6568.0,https://cards.scryfall.io/small/front/e/7/e718...,https://cards.scryfall.io/normal/front/e/7/e71...,https://cards.scryfall.io/large/front/e/7/e718...,https://cards.scryfall.io/png/front/e/7/e718b2...,https://cards.scryfall.io/art_crop/front/e/7/e...,https://cards.scryfall.io/border_crop/front/e/...,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,not_legal,legal,legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,not_legal,not_legal,0.39,None,None,0.36,None,1.05,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Road+of+Return,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/77122?affili...,oval,Magicshibby,https://www.youtube.com/watch?v=39MC2wBcf00&t=...,2019-08-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,card,036ef8c9-72ac-46ce-af07-83b79d736538,000d5588-5a4c-434e-988d-396632ade42c,[83282],22609.0,22610.0,12835.0,12551.0,Storm Crow,en,2005-07-29,https://api.scryfall.com/cards/036ef8c9-72ac-4...,https://scryfall.com/card/9ed/100/storm-crow?u...,normal,True,highres_scan,{1}{U},2.0,Creature — Bird,Flying (This creature can't be blocked except ...,[U],[U],[Flying],"[paper, mtgo]",False,False,True,[nonfoil],False,False,True,False,e70c8572-4732-4e92-a140-b4e3c1c84c93,9ed,Ninth Edition,core,https://api.scryfall.com/sets/e70c8572-4732-4e...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/9ed?utm_source=api,https://api.scryfall.com/cards/036ef8c9-72ac-4...,https://api.scryfall.com/cards/search?order=re...,100,False,common,"Storm crow descending, winter unending. Storm ...",0aeebaf5-8c7d-4636-9e82-8c27447861f7,John Matson,[a1685587-4b55-446b-b420-c37b202ed3f1],d01aa92b-0582-4e1e-a7b0-737b2ad4e462,white,2003,False,False,True,False,16956.0,https://cards.scryfall.io/small/front/0/3/036e...,https://cards.scryfall.io/normal/front/0/3/036...,https://cards.scryfall.io/large/front/0/3/036e...,https://cards.scryfall.io/png/front/0/3/036ef8...,https://cards.scryfall.io/art_crop/front/0/3/0...,https://cards.scryfall.io/border_crop/front/0/...,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,not_legal,not_legal,legal,legal,not_legal,legal,legal,0.24,None,None,0.04,None,0.04,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Storm+Crow,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/22609?affili...,NaN,NaN,NaN,NaN,1,2,12388.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,card,6010d06b-33b6-4631-9b3f-192d8c6b96e7,000d8291-d6a8-436e-9e17-7531333686a8,[],NaN,NaN,NaN,NaN,Snarlfang Vermin,en,2024-03-05,https://api.scryfall.com/cards/6010d06b-33b6-4...,https://scryfall.com/card/ymkm/12/snarlfang-ve...,normal,True,highres_scan,{B},1.0,Creature — Rat,Whenever Snarlfang Vermin deals combat damage ...,[B],[B],[],[arena],False,False,True,[nonfoil],False,False,False,False,3879667a-f0b8-4bc2-8662-7c861e22b4e9,ymkm,Alchemy: Murders at Karlov Manor,alchemy,https://api.scryfall.com/sets/3879667a-f0b8-4b...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/ymkm?utm_source=api,https://api.scryfall.com/cards/6010d06b-33b6-4...,https://api.scryfall.com/cards/search?order=re...,12,True,uncommon,NaN,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Ernanda Souza,[e87a8b19-f97f-4df0-9dda-1310ab0257bb],a34dcd37-7f1d-41ef-85a0-dc537c360a4a,black,2015,False,False,False,False,NaN,https://cards.scryfall.io/small/front/6/0/6010...,https://cards.scryfall.io/normal/front/6/0/601...,https://cards.scryfall.io/large/front/6/0/6010...,https://cards.scryfall.io/png/front/6/0/6010d0...,https://cards.scryfall.io/art_crop/front/6/0/6...,https://cards.scryfall.io/border_crop/front/6/...,not_legal,not_legal,legal,legal,legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,legal,legal,not_legal,not_legal,not_legal,not_legal,not_legal,None,None,None,None,None,None,NaN,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Snarlfang+Vermin,NaN,NaN,NaN,arena,NaN,NaN,NaN,2,1,NaN,91397.0,[alchemy],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32018,card,d6695fa8-881c-407c-91d9-3ac770372d35,fffa9334-3576-4f70-9605-2ad062cdbc69,[430770],64646.0,64647.0,136683.0,298834.0,Without Weakness,en,2017-07-14,https://api.scryfall.com/cards/d6695fa8-881c-4...,https://scryfall.com/card/hou/81/without-weakn...,normal,True,highres_scan,{1}{B},2.0,Instant,Target creature you control gains indestructib...,[B],[B],[Cycling],"[paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,False,False,65ff168b-bb94-47a5-a8f9-4ec6c213e768,hou,Hour of Devastation,expansion,https://api.scryfall.com/sets/65ff168b-bb94-47...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/hou?utm_source=api,https://api.scryfall.com/cards/d6695fa8-881c-4...,https://api.scryfall.com/cards/search?order=re...,81,False,common,NaN,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Alex Konstad,[58b2a57c-50ca-4047-b4e7-efb28cb22851],7e1d75ed-f0f9-4186-8c44-9f6ec354b2fa,black,2015,False,False,True,False,12661.0,https://cards.scryfall.io/small/front/d/6/d669...,https://cards.scryfall.io/normal/front/d/6/d66...,https://cards.scryfall.io/large/front/d/6/d669...,https://cards.scryfall.io/png/front/d/6/d6695f...,https://cards.scryfall.io/art_crop/front/d/6/d...,https://cards.scryfall.io/border_crop/front/d/...,not_legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,not_legal,not_legal,legal,legal,not_legal,not_legal,not_legal,0.03,0.32,None,0.11,0.14,0.03,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Without+Weakness,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/64646?affili...,NaN,NaN,NaN,NaN,NaN,NaN,10651.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32019,card,4d5edf4f-5695-42fc-9e57-c4faef60fbc3,fffaa634-42a0-4038-b027-24f28754fec7,[571548],101914.0,NaN,276869.0,665173.0,Firesong and Sunspeaker,en,2022-07-08,https://api.scryfall.com/cards/4d5edf4f-5695-4...,https://scryfall.com/card/2x2/215/firesong-and...,normal,True,highres_scan,{4}{R}{W},6.0,Legendary Creature — Minotaur Cleric,Red instant and sorcery spells you control hav...,"[R, W]","[R, W]",[],"[paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,True,False,5a645837-b050-449f-ac90-1e7ccbf45031,2x2,Double Masters 2022,masters,https://api.scryfall.com/sets/5a645837-b050-44...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/2x2?utm_source=api,https://api.scryfall.com/cards/4d5edf4f-5695-4...,https://api.scryfall.com/cards/search?order=re...,215,False,rare,The peaks of Hurloon never fall silent.,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Zoltan Boros,[1885e6cb-c827-4896-994e-3d0a027d602f],27ff1cb8-aaf8-4534-80ce-a4312e692bfe,black,2015,False,False,True,False,8269.0,https://cards.scryfall.io/small/front/4/d/4d5e...,https://cards.scryfall.io/normal/front/4/d/4d5...,https://cards.scryfall.io/large/front/4/d/4d5e...,https://cards.scryfall.io/png/front/4/d/4d5edf...,https://cards.scryfall.io/art_crop/front/4/d/4...,https://cards.scryfall.io/border_crop/front/4/...,not_legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,legal,legal,legal,legal,not_legal,legal,not_legal,not_legal,legal,not_legal,not_legal,not_legal,0.17,0.23,None,0.32,0.48,0.02,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Firesong+and+Suns...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/101914?affil...,oval,Wizards of the Coast,https://cafe.naver.com/mtgkr?iframe_url_utf8=%...,2022-06-22,4,6,NaN,NaN,NaN,NaN,[legendary],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32020,card,22a6a5f1-1405-4efb-af3e-e1f58d664e99,fffcb71f-e802-436e-917d-eaa6607ab74f,"[503766, 503767]",87643.0,NaN,230214.0,530502.0,"Toralf, God of Fury // Toralf's Hammer",en,2021-02-05,https://api.scryfall.com/cards/22a6a5f1-1405-4...,https://scryfall.com/card/khm/154/toralf-god-o...,modal_dfc,True,highres_scan,NaN,4.0,Legendary Creature — God // Legendary Artifact...,NaN,NaN,[R],"[Trample, Equip]","[arena, paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,False,False,43057fad-b1c1-437f-bc48-0045bce6d8c9,khm,Kaldheim,expansion,https://api.scryfall.com/sets/43057fad-b1c1-43...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/khm?utm_source=api,https://api.scryfall.com/cards/22a6a5f1-1405-4...,https://api.scryfall.com/cards/search?order=re...,154,False,mythic,NaN,NaN,Tyler Jacobson,[522af130-8db4-4b4b-950c-6e2b246339cf],NaN,black,2015,False,False,True,False,2816.0,NaN,NaN,NaN,NaN,NaN,NaN,not_legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,legal,legal,legal,legal,not_legal,legal,not_legal,not_legal,legal,not_legal,not_legal,not_legal,3.80,3.56,None,1.68,2.40,0.02,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Toralf%2C+God+of+...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/87643?affili...,oval,Wizards of the Coast,https://magic.wizards.com/en/articles/archive/...,2021-01-11,NaN,NaN,14251.0,75197.0,NaN,NaN,[legendary],NaN,NaN,"[{'object': 'card_face', 'name': 'Toralf, God ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
32021,card,09f06f55-7918-46c4-80ff-0bf39e091a4a,fffdc2ac-bde4-4e4c-a5bd-0e6c6e49ad91,[430833],64772.0,64773.0,132234.0,298282.0,"Samut, the Tested",en,2017-07-14,https://api.scryfall.com/cards/09f06f55-7918-4...,https://scryfall.com/card/hou/144/samut-the-te...,normal,True,highres_scan,{2}{R}{G},4.0,Legendary Planeswalker — Samut,+1: Up to one target creature gains double str...,"[G, R]","[G, R]",[],"[paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,False,False,65ff168b-bb94-47a5-a8f9-4ec6c213e768,hou,Hour of Devastation,expansion,https://api.scryfall.com/sets/65ff168b-bb94-47...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/hou?utm_source=api,https://api.scryfall.com/cards/09f06f55-7918-4...,https://api.scryfall.com/cards/search?order=re...,144,False,mythic,NaN,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Aleksi Briclot,[5e470014-31cb-41b0-b054-e23374484449],81028761-8670-42fe-a5f1-dc49d0c87440,black,2015,False,False,True,False,12389.0,https://cards.scryfall.io/small/front/0/9/09f0...,https://cards.scryfall.io/normal/front/0/9/09f...,https://cards.scryfall.io/large/front/0/9/09f0...,https://cards.scryfall.io/png/front/0/9/09f06f...,https://cards.scryfall.io/art_crop/front/0/9/0...,https://cards.scryfall.io/border_crop/front/0/...,not_legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,legal,legal,legal,legal,not_legal,legal,not_legal,not_legal,legal,not_legal,not_legal,not_legal,0.63,1.38,None,0.77,1.62,0.02,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Samut%2C+the+Tested,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/64772?affili...,oval,NaN,NaN,NaN,NaN,NaN,6512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN

In [63]:
csv_file_name = 'scryfall.csv'

if generate_data:
    #data via https://scryfall.com/docs/api/bulk-data; bulk data used to prevent too many API calls
    scryfall = open('scryfall.json', encoding="utf8")
    scryfall = json.load(scryfall)
    scryfall = pd.json_normalize(scryfall)
    scryfall.to_csv(csv_file_name, encoding='utf-8', index=False)
else:
    print("Data already made, skipping writing process")
    scryfall = pd.read_csv(csv_file_name) 
    scryfall.head(5)

In [64]:
scryfall

,object,id,oracle_id,multiverse_ids,mtgo_id,mtgo_foil_id,tcgplayer_id,cardmarket_id,name,lang,released_at,uri,scryfall_uri,layout,highres_image,image_status,mana_cost,cmc,type_line,oracle_text,colors,color_identity,keywords,games,reserved,foil,nonfoil,finishes,oversized,promo,reprint,variation,set_id,set,set_name,set_type,set_uri,set_search_uri,scryfall_set_uri,rulings_uri,prints_search_uri,collector_number,digital,rarity,flavor_text,card_back_id,artist,artist_ids,illustration_id,border_color,frame,full_art,textless,booster,story_spotlight,edhrec_rank,image_uris.small,image_uris.normal,image_uris.large,image_uris.png,image_uris.art_crop,image_uris.border_crop,legalities.standard,legalities.future,legalities.historic,legalities.timeless,legalities.gladiator,legalities.pioneer,legalities.explorer,legalities.modern,legalities.legacy,legalities.pauper,legalities.vintage,legalities.penny,legalities.commander,legalities.oathbreaker,legalities.standardbrawl,legalities.brawl,legalities.alchemy,legalities.paupercommander,legalities.duel,legalities.oldschool,legalities.premodern,legalities.predh,prices.usd,prices.usd_foil,prices.usd_etched,prices.eur,prices.eur_foil,prices.tix,related_uris.gatherer,related_uris.tcgplayer_infinite_articles,related_uris.tcgplayer_infinite_decks,related_uris.edhrec,purchase_uris.tcgplayer,purchase_uris.cardmarket,purchase_uris.cardhoarder,security_stamp,preview.source,preview.source_uri,preview.previewed_at,power,toughness,penny_rank,arena_id,promo_types,all_parts,frame_effects,produced_mana,watermark,card_faces,tcgplayer_etched_id,loyalty,life_modifier,hand_modifier,attraction_lights,color_indicator,content_warning
0,card,86bf43b1-8d4e-4759-bb2d-0b2e03ba7012,0004ebd0-dfd6-4276-b4a6-de0003e94237,[15862],15870.0,15871.0,3094.0,3081.0,Static Orb,en,2001-04-11,https://api.scryfall.com/cards/86bf43b1-8d4e-4...,https://scryfall.com/card/7ed/319/static-orb?u...,normal,True,highres_scan,{3},3.0,Artifact,"As long as Static Orb is untapped, players can...",[],[],[],"[paper, mtgo]",False,False,True,[nonfoil],False,False,True,False,230f38aa-9511-4db8-a3aa-aeddbc3f7bb9,7ed,Seventh Edition,core,https://api.scryfall.com/sets/230f38aa-9511-4d...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/7ed?utm_source=api,https://api.scryfall.com/cards/86bf43b1-8d4e-4...,https://api.scryfall.com/cards/search?order=re...,319,False,rare,The warriors fought against the paralyzing wav...,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Terese Nielsen,[eb55171c-2342-45f4-a503-2d5a75baf752],6f8b3b2c-252f-4f95-b621-712c82be38b5,white,1997,False,False,True,False,3863.0,https://cards.scryfall.io/small/front/8/6/86bf...,https://cards.scryfall.io/normal/front/8/6/86b...,https://cards.scryfall.io/large/front/8/6/86bf...,https://cards.scryfall.io/png/front/8/6/86bf43...,https://cards.scryfall.io/art_crop/front/8/6/8...,https://cards.scryfall.io/border_crop/front/8/...,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,not_legal,legal,legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,legal,19.41,None,None,9.42,None,0.24,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Static+Orb,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/15870?affili...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,card,7050735c-b232-47a6-a342-01795bfd0d46,0006faf6-7a61-426c-9034-579f2cfcfa83,[370780],49283.0,49284.0,69965.0,262945.0,Sensory Deprivation,en,2013-07-19,https://api.scryfall.com/cards/7050735c-b232-4...,https://scryfall.com/card/m14/71/sensory-depri...,normal,True,highres_scan,{U},1.0,Enchantment — Aura,Enchant creature\nEnchanted creature gets -3/-0.,[U],[U],[Enchant],"[paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,True,False,e03ee1c0-ecd2-4fcc-ac3c-e8fdb103a847,m14,Magic 2014,core,https://api.scryfall.com/sets/e03ee1c0-ecd2-4f...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/m14?utm_source=api,https://api.scryfall.com/cards/7050735c-b232-4...,https://api.scryfall.com/cards/search?order=re...,71,False,common,"They call it ""stitcher's anesthesia,"" a spell ...",0aeebaf5-8c7d-4636-9e82-8c27447861f7,Steven Belledin,[f07d73b9-52a0-4fe5-858b-61f7b42174a5],3c9e9355-4dcd-411c-b85f-47386e94854b,black,2003,False,False,True,False,25688.0,https://cards.scryfall.io/small/front/7/0/7050...,https://cards.scryfall.io/normal/front/7/0/705...,https://cards.scryfall.io/large/front/7/0/7050...,https://cards.scryfall.io/png/front/7/0/705073...,https://cards.scryfall.io/art_crop/front/7/0/7...,https://cards.scryfall.io/border_crop/front/7/...,not_legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,not_legal,not_legal,legal,legal,not_legal,not_legal,not_legal,0.04,0.21,None,0.07,0.17,0.04,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Sensory+Deprivation,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/49283?affili...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,card,e718b21b-46d1-4844-985c-52745657b1ac,0007c283-5b7a-4c00-9ca1-b455c8dff8c3,[470580],77122.0,NaN,196536.0,391692.0,Road of Return,en,2019-08-23,https://api.scryfall.com/cards/e718b21b-46d1-4...,https://scryfall.com/card/c19/34/road-of-retur...,normal,True,highres_scan,{G}{G},2.0,Sorcery,Choose one —\n• Return target permanent card f...,[G],[G],[Entwine],"[paper, mtgo]",False,False,True,[nonfoil],False,False,False,False,0fa3ccbb-d86d-4a2e-a55e-c4979c4feeb2,c19,Commander 2019,commander,https://api.scryfall.com/sets/0fa3ccbb-d86d-4a...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/c19?utm_source=api,https://api.scryfall.com/cards/e718b21b-46d1-4...,https://api.scryfall.com/cards/search?order=re...,34,False,rare,NaN,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Jonas De Ro,[561ebf9e-8d93-4b57-8156-8826d0c19601],279f7cef-a81c-4b43-98a0-937f3c355b5e,black,2015,False,False,False,False,6568.0,https://cards.scryfall.io/small/front/e/7/e718...,https://cards.scryfall.io/normal/front/e/7/e71...,https://cards.scryfall.io/large/front/e/7/e718...,https://cards.scryfall.io/png/front/e/7/e718b2...,https://cards.scryfall.io/art_crop/front/e/7/e...,https://cards.scryfall.io/border_crop/front/e/...,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,not_legal,legal,legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,not_legal,not_legal,0.39,None,None,0.36,None,1.05,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Road+of+Return,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/77122?affili...,oval,Magicshibby,https://www.youtube.com/watch?v=39MC2wBcf00&t=...,2019-08-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,card,036ef8c9-72ac-46ce-af07-83b79d736538,000d5588-5a4c-434e-988d-396632ade42c,[83282],22609.0,22610.0,12835.0,12551.0,Storm Crow,en,2005-07-29,https://api.scryfall.com/cards/036ef8c9-72ac-4...,https://scryfall.com/card/9ed/100/storm-crow?u...,normal,True,highres_scan,{1}{U},2.0,Creature — Bird,Flying (This creature can't be blocked except ...,[U],[U],[Flying],"[paper, mtgo]",False,False,True,[nonfoil],False,False,True,False,e70c8572-4732-4e92-a140-b4e3c1c84c93,9ed,Ninth Edition,core,https://api.scryfall.com/sets/e70c8572-4732-4e...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/9ed?utm_source=api,https://api.scryfall.com/cards/036ef8c9-72ac-4...,https://api.scryfall.com/cards/search?order=re...,100,False,common,"Storm crow descending, winter unending. Storm ...",0aeebaf5-8c7d-4636-9e82-8c27447861f7,John Matson,[a1685587-4b55-446b-b420-c37b202ed3f1],d01aa92b-0582-4e1e-a7b0-737b2ad4e462,white,2003,False,False,True,False,16956.0,https://cards.scryfall.io/small/front/0/3/036e...,https://cards.scryfall.io/normal/front/0/3/036...,https://cards.scryfall.io/large/front/0/3/036e...,https://cards.scryfall.io/png/front/0/3/036ef8...,https://cards.scryfall.io/art_crop/front/0/3/0...,https://cards.scryfall.io/border_crop/front/0/...,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,not_legal,not_legal,legal,legal,not_legal,legal,legal,0.24,None,None,0.04,None,0.04,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Storm+Crow,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/22609?affili...,NaN,NaN,NaN,NaN,1,2,12388.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,card,6010d06b-33b6-4631-9b3f-192d8c6b96e7,000d8291-d6a8-436e-9e17-7531333686a8,[],NaN,NaN,NaN,NaN,Snarlfang Vermin,en,2024-03-05,https://api.scryfall.com/cards/6010d06b-33b6-4...,https://scryfall.com/card/ymkm/12/snarlfang-ve...,normal,True,highres_scan,{B},1.0,Creature — Rat,Whenever Snarlfang Vermin deals combat damage ...,[B],[B],[],[arena],False,False,True,[nonfoil],False,False,False,False,3879667a-f0b8-4bc2-8662-7c861e22b4e9,ymkm,Alchemy: Murders at Karlov Manor,alchemy,https://api.scryfall.com/sets/3879667a-f0b8-4b...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/ymkm?utm_source=api,https://api.scryfall.com/cards/6010d06b-33b6-4...,https://api.scryfall.com/cards/search?order=re...,12,True,uncommon,NaN,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Ernanda Souza,[e87a8b19-f97f-4df0-9dda-1310ab0257bb],a34dcd37-7f1d-41ef-85a0-dc537c360a4a,black,2015,False,False,False,False,NaN,https://cards.scryfall.io/small/front/6/0/6010...,https://cards.scryfall.io/normal/front/6/0/601...,https://cards.scryfall.io/large/front/6/0/6010...,https://cards.scryfall.io/png/front/6/0/6010d0...,https://cards.scryfall.io/art_crop/front/6/0/6...,https://cards.scryfall.io/border_crop/front/6/...,not_legal,not_legal,legal,legal,legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,not_legal,legal,legal,not_legal,not_legal,not_legal,not_legal,not_legal,None,None,None,None,None,None,NaN,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Snarlfang+Vermin,NaN,NaN,NaN,arena,NaN,NaN,NaN,2,1,NaN,91397.0,[alchemy],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32018,card,d6695fa8-881c-407c-91d9-3ac770372d35,fffa9334-3576-4f70-9605-2ad062cdbc69,[430770],64646.0,64647.0,136683.0,298834.0,Without Weakness,en,2017-07-14,https://api.scryfall.com/cards/d6695fa8-881c-4...,https://scryfall.com/card/hou/81/without-weakn...,normal,True,highres_scan,{1}{B},2.0,Instant,Target creature you control gains indestructib...,[B],[B],[Cycling],"[paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,False,False,65ff168b-bb94-47a5-a8f9-4ec6c213e768,hou,Hour of Devastation,expansion,https://api.scryfall.com/sets/65ff168b-bb94-47...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/hou?utm_source=api,https://api.scryfall.com/cards/d6695fa8-881c-4...,https://api.scryfall.com/cards/search?order=re...,81,False,common,NaN,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Alex Konstad,[58b2a57c-50ca-4047-b4e7-efb28cb22851],7e1d75ed-f0f9-4186-8c44-9f6ec354b2fa,black,2015,False,False,True,False,12661.0,https://cards.scryfall.io/small/front/d/6/d669...,https://cards.scryfall.io/normal/front/d/6/d66...,https://cards.scryfall.io/large/front/d/6/d669...,https://cards.scryfall.io/png/front/d/6/d6695f...,https://cards.scryfall.io/art_crop/front/d/6/d...,https://cards.scryfall.io/border_crop/front/d/...,not_legal,not_legal,not_legal,not_legal,not_legal,legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,not_legal,not_legal,legal,legal,not_legal,not_legal,not_legal,0.03,0.32,None,0.11,0.14,0.03,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Without+Weakness,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/64646?affili...,NaN,NaN,NaN,NaN,NaN,NaN,10651.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32019,card,4d5edf4f-5695-42fc-9e57-c4faef60fbc3,fffaa634-42a0-4038-b027-24f28754fec7,[571548],101914.0,NaN,276869.0,665173.0,Firesong and Sunspeaker,en,2022-07-08,https://api.scryfall.com/cards/4d5edf4f-5695-4...,https://scryfall.com/card/2x2/215/firesong-and...,normal,True,highres_scan,{4}{R}{W},6.0,Legendary Creature — Minotaur Cleric,Red instant and sorcery spells you control hav...,"[R, W]","[R, W]",[],"[paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,True,False,5a645837-b050-449f-ac90-1e7ccbf45031,2x2,Double Masters 2022,masters,https://api.scryfall.com/sets/5a645837-b050-44...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/2x2?utm_source=api,https://api.scryfall.com/cards/4d5edf4f-5695-4...,https://api.scryfall.com/cards/search?order=re...,215,False,rare,The peaks of Hurloon never fall silent.,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Zoltan Boros,[1885e6cb-c827-4896-994e-3d0a027d602f],27ff1cb8-aaf8-4534-80ce-a4312e692bfe,black,2015,False,False,True,False,8269.0,https://cards.scryfall.io/small/front/4/d/4d5e...,https://cards.scryfall.io/normal/front/4/d/4d5...,https://cards.scryfall.io/large/front/4/d/4d5e...,https://cards.scryfall.io/png/front/4/d/4d5edf...,https://cards.scryfall.io/art_crop/front/4/d/4...,https://cards.scryfall.io/border_crop/front/4/...,not_legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,legal,legal,legal,legal,not_legal,legal,not_legal,not_legal,legal,not_legal,not_legal,not_legal,0.17,0.23,None,0.32,0.48,0.02,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Firesong+and+Suns...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/101914?affil...,oval,Wizards of the Coast,https://cafe.naver.com/mtgkr?iframe_url_utf8=%...,2022-06-22,4,6,NaN,NaN,NaN,NaN,[legendary],NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32020,card,22a6a5f1-1405-4efb-af3e-e1f58d664e99,fffcb71f-e802-436e-917d-eaa6607ab74f,"[503766, 503767]",87643.0,NaN,230214.0,530502.0,"Toralf, God of Fury // Toralf's Hammer",en,2021-02-05,https://api.scryfall.com/cards/22a6a5f1-1405-4...,https://scryfall.com/card/khm/154/toralf-god-o...,modal_dfc,True,highres_scan,NaN,4.0,Legendary Creature — God // Legendary Artifact...,NaN,NaN,[R],"[Trample, Equip]","[arena, paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,False,False,43057fad-b1c1-437f-bc48-0045bce6d8c9,khm,Kaldheim,expansion,https://api.scryfall.com/sets/43057fad-b1c1-43...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/khm?utm_source=api,https://api.scryfall.com/cards/22a6a5f1-1405-4...,https://api.scryfall.com/cards/search?order=re...,154,False,mythic,NaN,NaN,Tyler Jacobson,[522af130-8db4-4b4b-950c-6e2b246339cf],NaN,black,2015,False,False,True,False,2816.0,NaN,NaN,NaN,NaN,NaN,NaN,not_legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,legal,legal,legal,legal,not_legal,legal,not_legal,not_legal,legal,not_legal,not_legal,not_legal,3.80,3.56,None,1.68,2.40,0.02,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Toralf%2C+God+of+...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/87643?affili...,oval,Wizards of the Coast,https://magic.wizards.com/en/articles/archive/...,2021-01-11,NaN,NaN,14251.0,75197.0,NaN,NaN,[legendary],NaN,NaN,"[{'object': 'card_face', 'name': 'Toralf, God ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN
32021,card,09f06f55-7918-46c4-80ff-0bf39e091a4a,fffdc2ac-bde4-4e4c-a5bd-0e6c6e49ad91,[430833],64772.0,64773.0,132234.0,298282.0,"Samut, the Tested",en,2017-07-14,https://api.scryfall.com/cards/09f06f55-7918-4...,https://scryfall.com/card/hou/144/samut-the-te...,normal,True,highres_scan,{2}{R}{G},4.0,Legendary Planeswalker — Samut,+1: Up to one target creature gains double str...,"[G, R]","[G, R]",[],"[paper, mtgo]",False,True,True,"[nonfoil, foil]",False,False,False,False,65ff168b-bb94-47a5-a8f9-4ec6c213e768,hou,Hour of Devastation,expansion,https://api.scryfall.com/sets/65ff168b-bb94-47...,https://api.scryfall.com/cards/search?order=se...,https://scryfall.com/sets/hou?utm_source=api,https://api.scryfall.com/cards/09f06f55-7918-4...,https://api.scryfall.com/cards/search?order=re...,144,False,mythic,NaN,0aeebaf5-8c7d-4636-9e82-8c27447861f7,Aleksi Briclot,[5e470014-31cb-41b0-b054-e23374484449],81028761-8670-42fe-a5f1-dc49d0c87440,black,2015,False,False,True,False,12389.0,https://cards.scryfall.io/small/front/0/9/09f0...,https://cards.scryfall.io/normal/front/0/9/09f...,https://cards.scryfall.io/large/front/0/9/09f0...,https://cards.scryfall.io/png/front/0/9/09f06f...,https://cards.scryfall.io/art_crop/front/0/9/0...,https://cards.scryfall.io/border_crop/front/0/...,not_legal,not_legal,legal,legal,legal,legal,legal,legal,legal,not_legal,legal,legal,legal,legal,not_legal,legal,not_legal,not_legal,legal,not_legal,not_legal,not_legal,0.63,1.38,None,0.77,1.62,0.02,https://gatherer.wizards.com/Pages/Card/Detail...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://edhrec.com/route/?cc=Samut%2C+the+Tested,https://tcgplayer.pxf.io/c/4931599/1830156/210...,https://www.cardmarket.com/en/Magic/Products/S...,https://www.cardhoarder.com/cards/64772?affili...,oval,NaN,NaN,NaN,NaN,NaN,6512.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,NaN,NaN,NaN,NaN,NaN

In [ ]:
#hardcode the ban list (this has cards post 2018 in case we ever change what time period we look at)
#any card
["Ancient Den", "Arcum's Astrolabe", "Birthing Pod", "Blazing Shoal", "Bridge From Below", "Chrome Mox", "Cloudpost", "Dark Depths", "Deathrite Shaman", "Dig Through Time", "Dread Return", "Eye of Ugin", "Faithless Looting", "Field of the Dead", "Fury", "Gitaxian Probe", "Glimpse of Nature", "Golgari Grave-Troll", "Great Furnace", "Green Sun's Zenith", "Hogaak, Arisen Necropolis", "Hypergenesis", "Krark-Clan Ironworks", "Lurrus of the Dream-Den", "Mental Misstep", "Mox Opal", "Mycosynth Lattice", "Mystic Sanctuary", "Oko, Thief of Crowns", "Once Upon a Time", "Ponder", "Punishing Fire", "Rite of Flame", "Seat of the Synod", "Second Sunrise", "Seething Song", "Sensei's Divining Top", "Simian Spirit Guide", "Skullclamp", "Splinter Twin", "Summer Bloom", "Tibalt's Trickery", "Treasure Cruise", "Tree of Tales", "Umezawa's Jitte", "Up the Beanstalk", "Uro, Titan of Nature's Wrath", "Vault of Whispers", "Violent Outburst", "Yorion, Sky Nomad"]

In [ ]:
scryfall.loc[(scryfall['lang'] == 'en') & (scryfall['released_at'] <= '2019-01-01') & (scryfall['name'] == 'Storm Crow')]

In [ ]:
scryfall['lang'].unique()

In [ ]:
pd.json_normalize(scryfall)

In [ ]:
### Weighing System for Cards ###

In [ ]:
# type of tournament
# number of copies
# main vs side deck
# was the card eventually banned
# length of time card was legal in the format (so new cards)
# card type (empthasis on lands)
# mana value
# color

In [ ]:
tournament_weight = tournament_decklists['tournament_name'].value_counts().reset_index(name='count')
tournament_weight.rename({'index':'tournament_name'}, axis = 1, inplace = True)

tournament_weight['total_percent'] = round(tournament_weight['count'] / len(tournament_decklists),4)
tournament_weight